[package]
name = "seshat"
version = "2.2.1"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "Apache-2.0"
description = "A matrix message logger with full text search support"
readme="README.md"
repository="https://github.com/matrix-org/seshat/"

[features]
default = ["encryption"]
encryption = ["rusqlite/sqlcipher", "aes-ctr", "crypto-mac", "hmac", "sha2",
              "hkdf", "pbkdf2", "rand", "zeroize", "byteorder"]

[dependencies]
tantivy = "0.12.0"
tinysegmenter = "0.1.1"
rusqlite = "0.23.1"
fs_extra = "1.1.0"
r2d2_sqlite = "0.16.0"
r2d2 = "0.8.8"
lru-cache = "0.1.2"
uuid = { version = "0.8.1", features = ["v4"] }

aes-ctr = { version = "0.3.0", optional = true }
crypto-mac = { version = "0.7.0", optional = true }
hmac = { version = "0.7.1", optional = true }
sha2 = { version = "0.8.2", optional = true }
hkdf = { version = "0.8.0", optional = true }
pbkdf2 = { version = "0.3.0", optional = true }
rand = { version = "0.7.3", optional = true }
zeroize = { version = "1.1.0", optional = true }
byteorder = { version = "1.3.4", optional = true }

serde_json = "1.0.53"
serde = { version = "1.0.110", default-features = false, features = ["derive"] }
thiserror = "1.0.19"

[dev-dependencies]
tempfile = "3.1.0"
lazy_static = "1.4.0"
fake = "2.2.2"
base64 = "0.12.3"
