name: CI

on:
  push:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  style:
    name: Check style
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Install rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt

    - name: Cargo fmt
      run: |
        cargo fmt -- --check

  clippy:
    name: Run clippy
    needs: [style]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Install rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: clippy

    - name: Clippy
      run: |
        cargo clippy --all-targets -- -D warnings

  build-test:
    name: ${{ matrix.name }}
    needs: [clippy]

    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    strategy:
      matrix:
        name:
          - linux / stable
          - linux / beta
          - macOS / stable

        include:
          - name: linux / stable

          - name: linux / beta
            rust: beta

          - name: macOS / stable
            os: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust || 'stable' }}
          target: ${{ matrix.target }}

      - name: Build Rust
        run: |
          cargo build --features=bundled-sqlcipher

      - name: Test Rust
        run: |
          cargo test --features=bundled-sqlcipher

      # Checkout again to reset the test DB state
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install node build dependencies
        run: cd seshat-node && yarn install

      - name: Build node module
        run: cd seshat-node && yarn run build-bundled

      - name: Test node module
        run: cd seshat-node && yarn run test
